### ISSUE TITLE
Deprecate in favor of RackAttack

### ISSUE THREAD

**Issue by FreekingDean** [dryruby/rack-throttle#43]
Hello All!

I wanted to open discussion to see if RackAttack could serve the wonderful people using this lovely gem a bit better. https://github.com/kickstarter/rack-attack

It seems to hame more features/functionality/community than here at rack-throttle & I'm thinking we may want to give up the throne to help peoples looking for this functionality & have come here :)

@bendiken @brandonhilkert + any others, thoughts?

**Comment by FreekingDean** [comment]
@TheWudu I would be interested to hear your thoughts on this. Since that project has much more activity I think it may be worth deprecating this in favor of that project?

**Comment by TheWudu** [comment]
Hello @FreekingDean ,

basically i think rack-attack also fulfills the criterias, but unfortunately it has a minimum ruby version of 2.3, which we basically have everywhere except ONE damn old legacy service, which needs the throtteling .. 

We are currently working on getting rid of it (instead of updating it) but it grew over years and is just huge. So whenever we got rid of that entirely we may also switch to rack-attack.

There is one more PR i created for the rack-throttle gem, which may be mergable into the master. I will open it soon. It enables proc-rules. 
https://github.com/TheWudu/rack-throttle/pull/1

I guess that would be the last (bigger) change we need. I hope we can get rid of the old project soon .. but as it is not entirely in my hands what i work on all day long .. and many people are involed in it, it may take some time.
